# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/immac/Documents/classes/current/compiladoresii/project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/immac/Documents/classes/current/compiladoresii/project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/immac/Documents/classes/current/compiladoresii/project/CMakeFiles /home/immac/Documents/classes/current/compiladoresii/project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/immac/Documents/classes/current/compiladoresii/project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bin/expr

# Build rule for target.
bin/expr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bin/expr
.PHONY : bin/expr

# fast build rule for target.
bin/expr/fast:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/build
.PHONY : bin/expr/fast

src/add-expression.o: src/add-expression.cpp.o
.PHONY : src/add-expression.o

# target to build an object file
src/add-expression.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/add-expression.cpp.o
.PHONY : src/add-expression.cpp.o

src/add-expression.i: src/add-expression.cpp.i
.PHONY : src/add-expression.i

# target to preprocess a source file
src/add-expression.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/add-expression.cpp.i
.PHONY : src/add-expression.cpp.i

src/add-expression.s: src/add-expression.cpp.s
.PHONY : src/add-expression.s

# target to generate assembly for a file
src/add-expression.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/add-expression.cpp.s
.PHONY : src/add-expression.cpp.s

src/assign-statement.o: src/assign-statement.cpp.o
.PHONY : src/assign-statement.o

# target to build an object file
src/assign-statement.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/assign-statement.cpp.o
.PHONY : src/assign-statement.cpp.o

src/assign-statement.i: src/assign-statement.cpp.i
.PHONY : src/assign-statement.i

# target to preprocess a source file
src/assign-statement.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/assign-statement.cpp.i
.PHONY : src/assign-statement.cpp.i

src/assign-statement.s: src/assign-statement.cpp.s
.PHONY : src/assign-statement.s

# target to generate assembly for a file
src/assign-statement.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/assign-statement.cpp.s
.PHONY : src/assign-statement.cpp.s

src/if-statement.o: src/if-statement.cpp.o
.PHONY : src/if-statement.o

# target to build an object file
src/if-statement.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/if-statement.cpp.o
.PHONY : src/if-statement.cpp.o

src/if-statement.i: src/if-statement.cpp.i
.PHONY : src/if-statement.i

# target to preprocess a source file
src/if-statement.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/if-statement.cpp.i
.PHONY : src/if-statement.cpp.i

src/if-statement.s: src/if-statement.cpp.s
.PHONY : src/if-statement.s

# target to generate assembly for a file
src/if-statement.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/if-statement.cpp.s
.PHONY : src/if-statement.cpp.s

src/lexer.o: src/lexer.cpp.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/lexer.cpp.o
.PHONY : src/lexer.cpp.o

src/lexer.i: src/lexer.cpp.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/lexer.cpp.i
.PHONY : src/lexer.cpp.i

src/lexer.s: src/lexer.cpp.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/lexer.cpp.s
.PHONY : src/lexer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/print-statement.o: src/print-statement.cpp.o
.PHONY : src/print-statement.o

# target to build an object file
src/print-statement.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/print-statement.cpp.o
.PHONY : src/print-statement.cpp.o

src/print-statement.i: src/print-statement.cpp.i
.PHONY : src/print-statement.i

# target to preprocess a source file
src/print-statement.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/print-statement.cpp.i
.PHONY : src/print-statement.cpp.i

src/print-statement.s: src/print-statement.cpp.s
.PHONY : src/print-statement.s

# target to generate assembly for a file
src/print-statement.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/print-statement.cpp.s
.PHONY : src/print-statement.cpp.s

src/while-statement.o: src/while-statement.cpp.o
.PHONY : src/while-statement.o

# target to build an object file
src/while-statement.cpp.o:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/while-statement.cpp.o
.PHONY : src/while-statement.cpp.o

src/while-statement.i: src/while-statement.cpp.i
.PHONY : src/while-statement.i

# target to preprocess a source file
src/while-statement.cpp.i:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/while-statement.cpp.i
.PHONY : src/while-statement.cpp.i

src/while-statement.s: src/while-statement.cpp.s
.PHONY : src/while-statement.s

# target to generate assembly for a file
src/while-statement.cpp.s:
	$(MAKE) -f CMakeFiles/bin/expr.dir/build.make CMakeFiles/bin/expr.dir/src/while-statement.cpp.s
.PHONY : src/while-statement.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... bin/expr"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/add-expression.o"
	@echo "... src/add-expression.i"
	@echo "... src/add-expression.s"
	@echo "... src/assign-statement.o"
	@echo "... src/assign-statement.i"
	@echo "... src/assign-statement.s"
	@echo "... src/if-statement.o"
	@echo "... src/if-statement.i"
	@echo "... src/if-statement.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/print-statement.o"
	@echo "... src/print-statement.i"
	@echo "... src/print-statement.s"
	@echo "... src/while-statement.o"
	@echo "... src/while-statement.i"
	@echo "... src/while-statement.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

